import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarProvider,
  SidebarTrigger
} from "@/components/ui/sidebar"
import AppSidebar from '@/components/AppSidebarComponent';
import { ClerkProvider } from '@clerk/nextjs';
import { auth } from '@clerk/nextjs/server';
import Provider from './provider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // NOTE - Get User ID
  const { userId } = await auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Provider >
            {
              userId ? (
                <SidebarProvider>
                  <AppSidebar />
                  <main
                    className="flex-1 flex items-center justify-center"
                  >
                    <SidebarTrigger
                      className="absolute left-4 top-4 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-background shadow-md hover:bg-accent hover:text-accent-foreground"
                    />
                    {children}
                  </main>
                </SidebarProvider>
              ) : (
                <main
                  className="flex-1 flex items-center justify-center"
                >
                  {children}
                </main>
              )
            }
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
